### PR TITLE
changed the config to increase and decrease brightness 

### PR DESCRIPTION
**Pull request by Pratyay360**
I have addressed the issue related to adjusting brightness in i3wm by implementing the 'brightnessctl' package in my configuration. This solution has resolved the problem with the laptop's brightness control button.

### CODE REVIEW

**Review by killajoe — CHANGES_REQUESTED** [review]
this should get into the packages file no need to add it here to get installed

**Comment by Pratyay360** [comment]
removed package `brightnessctl` from here to be added into the package file

**Comment by killajoe** [comment]
still this should be added as an commented option.

**Comment by Pratyay360** [comment]
have raised pull request in the package section

**Comment by killajoe** [comment]
The question about why it should be added and if the current implementation is causing any issue is still open.

**Comment by killajoe** [comment]
I would have no issue to add the option commented, with the info that it is alternative to the one that is set-up already.. and indeed that you will need to install the package to use the option. I will not change a working implementation and add packages to the list of the install process without any reason.

**Pull request closed without merging**
