### PR TITLE
[config] correction for xss-lock command line

### PR DESCRIPTION
**Pull request by killajoe**

### CODE REVIEW

**Comment by pprevos** [comment]
Thanks

**Comment by killajoe** [comment]
> Thanks

would be cool if you can validate.. i had some issues testing it but the command now should work, in cas ei do hibernate/suspend manually too and if system times out and screen goes sleep it locks too. 

Changes will not apply automatically to installed systems you will need to add the changes manually.

**Comment by pprevos** [comment]
Hi Johannes, I have copied the new config into mine and it works fine.

There is an error regarding the `blur-lock` script (In ImageMagick, `convert` is now `magick`). But I gather that is not in this repo.

Thanks for working on this.

**Comment by killajoe** [comment]
> Thanks

B.T.W: very nice to hint on the locker issue.. i love to have it now.

**Pull request merged**
